### ISSUE TITLE
Leader board

### ISSUE THREAD

**Issue by jacekplocharczyk** [nextgrid/dll-ideas#9]
- [ ] Local leader board for Warsaw DLL
- [ ] Local leader board for each DLL location
- [ ] Global leader board
- [ ] How to manage people who are changing teams? Teams leader board (for stable teams) and individual leader board (for participants)?

**Comment by Mindgames** [comment]
Closing this issue as the Leaderboard function will be included in https://github.com/nextgrid/dll-web-app
